### ISSUE TITLE
forced to use proton since the august 2023 build on native linux gmod does not work

### ISSUE THREAD

**Issue by Epic62790** [solsticegamestudios/GModCEFCodecFix#74] opened 2023-08-08 21:26 UTC
everyone else on linux is getting the same engine.so not found error

**Comment by AkikoKumagara** [comment] 2023-08-08 23:42
On days where GMod [x86-64] is updated, it's normal to have some downtime where patching doesn't work, until our manifest is regenerated to accommodate changes to file hashes. I have confirmed that this is indeed what the problem was here and it has since been resolved by the manifest regeneration that took place at around 1PM EDT.

You can try again and close your issue if everything is working now.

You may need to have some patience on days where GMod updates, as this is a likely scenario on those days.

**Closed** 2023-08-25 06:52 UTC
