### ISSUE TITLE
Recent version breaks OGG Vorbis for Gmod pls fix~

### ISSUE THREAD

**Issue by RazorWolvendom** [solsticegamestudios/GModCEFCodecFix#23] opened 2021-12-25 03:22 UTC
actually since the september release the patch makes it unable to hear OGG in gmod over the addon [PAC3] by linking a ogg file in the OGG part, otherwise ogg still works in the Webaudio part
![ScreenShot_20211225042223](https://user-images.githubusercontent.com/44827474/147376667-7f3bf5c3-8234-45b1-9453-2fb7a0c7e9a9.png)

without the patch ogg works fine in the OGG part
before the patch
<img width="338" alt="ScreenShot_20211225041213" src="https://user-images.githubusercontent.com/44827474/147376643-086f8d6d-e01d-4e09-90cf-dfa88cf1a0ad.png">

and after the patch
<img width="340" alt="ScreenShot_20211225041527" src="https://user-images.githubusercontent.com/44827474/147376647-1f21a88a-d2de-4030-a99b-f52f05dc718a.png">

since the patch includes to "fix" the gmod.exe there might be something blocked or removed which is important for the addon to work as it should

**Comment by WinterPhoenix** [comment] 2021-12-25 07:33
How is the OGG file being played? Through CEF?

**Comment by RazorWolvendom** [comment] 2021-12-25 21:34
> How is the OGG file being played in PAC3? Through CEF?

its actually a stream since it uses the Link of the file thats uploaded on a filehoster like Dropbox

**Comment by WinterPhoenix** [comment] 2021-12-27 23:42
So does it get played through CEF?

**Comment by RazorWolvendom** [comment] 2021-12-28 03:37
> So does it get played through CEF?

welp im not sure but PAC3 was always working regardless of the beta version bc PAC3 exists since like 2012, but like i said if i patch it you wont hear any OGG over the ogg function besides from the webaudio function which wasnt before since few previous updates of Codec

https://github.com/CapsAdmin/pac3
there you can take a look if you can find the coded line you need to know

**Comment by WinterPhoenix** [comment] 2021-12-28 21:32
Check your console. When PAC3 tries to play OGG, does it say anything like "OGG error?"

I have a tough time believing it's something GModCEFCodecFix is doing, as it seems like the Legacy OGG part in PAC3 just uses [IGModAudioChannel](https://wiki.facepunch.com/gmod/IGModAudioChannel)

**Comment by RazorWolvendom** [comment] 2021-12-29 00:35
no, no error at all since i know its something that Codecfix "changes" bc when i reset the game with verify game integrety it gets its original files back to "default" and then i can hear OGG normally as i should be able to, after patching there is just literally nothing i can hear of OGG.

i can gladly make you a "setup" pac with a ogg sound you can recreate with easy steps if you got time for it, since all the stuff is working without the patch, but without the patch i cant watch videos then.

verify game integrety to set the game back to the defaults (( only if you patched it already))

then

1. copy this pac save file i uploaded
( https://www.dropbox.com/s/q5tn4sox2j51wl2/pac3%20codec%20test.txt?dl=0 )
then you open the pac editor either by holding C and then clicking on the pac3 icon on the left side and then you see on the left side the pac3 window / tree editor

2. click on "pac" -> "load" -> "load from url" then you paste the copied link in that line and press Enter (the uploaded save file gets loaded then ((if a error appears try a 2nd time to load it)))

3. then just hold the button "R" and then you should hear this theme i choose for the test ( https://www.youtube.com/watch?v=EP62gl-sj2I&t=227s ) make sure that you are in Thirdperson to hear and see your own "pac"

4. after that then open pac again and click on "pac" -> "save" -> "new file" and name it as anything you want

5. then you patch the game again and then try again to hear the theme over the pac by open "pac" -> "load" -> "[name of the file as you saved it]" and hold R again while in thirdperson and you would notice that you hear nothing then if you followed the instructions correctly.

**Comment by WinterPhoenix** [comment] 2022-02-16 03:44
I was able to reproduce this. It's an issue with PAC3.

On startup, if you take a look at console, you'll notice this message:
```
[PAC3] [OGG] Uncaught ReferenceError: lua is not defined
```

Legacy OGG uses CEF through its `webaudio` interface. The new OGG part uses IGModAudioChannel.

Taking a look through the code, the issue is almost certainly the `AddFunction` calls:
https://github.com/CapsAdmin/pac3/blob/master/lua/pac3/libraries/webaudio/browser.lua#L55-L72

As part of CEF 93, the structure for doing callbacks was changed:
https://bitbucket.org/chromiumembedded/cef/commits/43f9baa23aeb92e6b73e3c72c8ab387b6012df16
https://bitbucket.org/chromiumembedded/cef/commits/07bc800f0080f62e0d299d3e1a878510085bebc3

Which meant we had to adapt how we do our stuff:
https://github.com/solsticegamestudios/gmod-html/commit/fd72e0358c92d7d95e3d0af0b42864835ce06457

I'm going to bet that change, picked up when we updated to CEF 95, is the cause of this. I don't know if it'll be fixed on PAC's end though, considering that it's a Legacy part.

**Closed** 2022-02-16 04:28 UTC
Labels: wontfix

**Comment by RazorWolvendom** [comment] 2022-02-16 19:32
> I was able to reproduce this. It's an issue with PAC3.
> 
> On startup, if you take a look at console, you'll notice this message:
> 
> ```
> [PAC3] [OGG] Uncaught ReferenceError: lua is not defined
> ```
> 
> Legacy OGG uses CEF through its `webaudio` interface. The new OGG part uses IGModAudioChannel.
> 
> Taking a look through the code, the issue is almost certainly the `AddFunction` calls: https://github.com/CapsAdmin/pac3/blob/master/lua/pac3/libraries/webaudio/browser.lua#L55-L72
> 
> As part of CEF 93, the structure for doing callbacks was changed: https://bitbucket.org/chromiumembedded/cef/commits/43f9baa23aeb92e6b73e3c72c8ab387b6012df16 https://bitbucket.org/chromiumembedded/cef/commits/07bc800f0080f62e0d299d3e1a878510085bebc3
> 
> Which meant we had to adapt how we do our stuff: [solsticegamestudios/gmod-html@fd72e03](https://github.com/solsticegamestudios/gmod-html/commit/fd72e0358c92d7d95e3d0af0b42864835ce06457)
> 
> I'm going to bet that change, picked up when we updated to CEF 95, is the cause of this. I don't know if it'll be fixed on PAC's end though, considering that it's a Legacy part.


https://github.com/CapsAdmin/pac3/issues/1144

have fun reading thier response~

**Comment by WinterPhoenix** [comment] 2022-02-16 21:22
> [CapsAdmin/pac3#1144](https://github.com/CapsAdmin/pac3/issues/1144)
> 
> have fun reading DBotThePony's response~

If they don't wanna fix it, they don't wanna fix it, I'm just the messenger lol
