### ISSUE TITLE
Cannot type in console/chat

### ISSUE THREAD

**Issue by Epic62790** [solsticegamestudios/GModCEFCodecFix#63] opened 2023-07-19 22:37 UTC
Fix this please. Im having this issue where i cant type.

**Comment by AkikoKumagara** [comment] 2023-07-19 22:40
This is a GMod issue which will require Facepunch to fix. We already have an issue opened. https://github.com/Facepunch/garrysmod-issues/issues/5434

**Comment by WinterPhoenix** [comment] 2023-07-19 22:43
Duplicate of #53

**Closed by WinterPhoenix** 2023-07-19 22:43 UTC
