### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by dnkmmr69420** [solsticegamestudios/GModCEFCodecFix#64] opened 2023-07-22 23:46 UTC
I can't find out how to run this for steam flatpak, this should get some flatpak support

**Comment by jtfen86** [comment] 2023-10-25 21:07
Snap support would be nice too!

**Comment by WinterPhoenix** [comment] 2023-10-26 02:55
> Snap support would be nice too!

@jtfen86 Please make a separate issue for this and report any issues you're having

**Comment by Aferz1337** [comment] 2024-02-11 22:12
Try this:
`ln -s ~/.var/app/com.valvesoftware.Steam/data/Steam/ ~/.local/share/`

**Comment by AkikoKumagara** [comment] 2024-02-12 01:38
> Try this: `ln -s ~/.var/app/com.valvesoftware.Steam/data/Steam/ ~/.local/share/` Worked for me

You shouldn't have to do this as we have built in detection for Flatpak's filepaths now. The problem is, though, that even though we can patch Flatpak installs now, they aren't working because of CEF's inability to launch inside of `bubblewrap`, the container Flatpak's run inside of.

If you had to make a symlink for the executable to run successfully, there may be something strange about your configuration that's not accounted for, such as a leftover appmanifest from an old Steam installation. Even so, patching won't do much for Flatpak users, though it is possible.

**Comment by WinterPhoenix** [comment] 2024-05-02 21:52
Should be fixed as of the [latest release](https://github.com/solsticegamestudios/GModCEFCodecFix/releases)

**Closed by WinterPhoenix** 2024-05-02 21:52 UTC
